In [ ]:
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Number of rows
num_rows = 200

# Generate synthetic data
data = {
    'Age': np.random.randint(20, 65, num_rows),
    'No. of Family Members': np.random.randint(3, 8, num_rows),
    'Total Dependents': np.random.randint(1, 5, num_rows),
    'No. of Earners': np.random.randint(1, 4, num_rows),
    'Income': np.random.randint(30000, 80000, num_rows),
    'Reason for Loan': np.random.randint(1, 5, num_rows),
}

# Create DataFrame
df = pd.DataFrame(data)

# Map Reason for Loan to the specified categories
df['Reason for Loan'] = df['Reason for Loan'].map({
    1: 'Life Expenses',
    2: 'Education',
    3: 'Business',
    4: 'Other'
})

# Add Loan Amount based on a simple linear regression-like relationship
df['Loan Amount'] = 300 + 20 * df['Income'] + 10 * df['Age'] - 5 * df['Total Dependents']

# Display the DataFrame
print(df)

     Age  No. of Family Members  Total Dependents  No. of Earners  Income  \
0     58                      5                 1               3   75106
1     48                      3                 2               2   47100
2     34                      4                 3               3   51949
3     62                      4                 3               1   34544
4     27                      6                 1               1   67744
..   ...                    ...               ...             ...     ...
195   58                      6                 4               1   40589
196   21                      4                 2               2   43918
197   22                      4                 3               1   50119
198   56                      7                 4               2   57446
199   36                      4                 4               1   43046

    Reason for Loan  Loan Amount
0          Business      1502995
1          Business       942770
2          Business      1039605
3             Other       691785
4     Life Expenses      1355445
..              ...          ...
195        Business       812640
196        Business       878860
197           Other      1002885
198   Life Expenses      1149760
199           Other       861560

[200 rows x 7 columns]

In [ ]:
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Number of rows
num_rows = 200

# Generate synthetic data
data = {
    'Age': np.random.randint(20, 65, num_rows),
    'No. of Family Members': np.random.randint(3, 8, num_rows),
    'Total Dependents': np.random.randint(1, 5, num_rows),
    'No. of Earners': np.random.randint(1, 4, num_rows),
    'Income': np.random.randint(30000, 80000, num_rows),
    'Reason for Loan': np.random.randint(1, 5, num_rows),
}

# Create DataFrame
df = pd.DataFrame(data)

# Map Reason for Loan to the specified categories
df['Reason for Loan'] = df['Reason for Loan'].map({
    1: 'Life Expenses',
    2: 'Education',
    3: 'Business',
    4: 'Other'
})

# Add Loan Amount based on a simple linear regression-like relationship
df['Loan Amount'] = 300 + 20 * df['Income'] + 10 * df['Age'] - 5 * df['Total Dependents']

# Display the entire DataFrame
df

,Age,No. of Family Members,Total Dependents,No. of Earners,Income,Reason for Loan,Loan Amount
0,58,5,1,3,75106,Business,1502995
1,48,3,2,2,47100,Business,942770
2,34,4,3,3,51949,Business,1039605
3,62,4,3,1,34544,Other,691785
4,27,6,1,1,67744,Life Expenses,1355445
...,...,...,...,...,...,...,...
195,58,6,4,1,40589,Business,812640
196,21,4,2,2,43918,Business,878860
197,22,4,3,1,50119,Other,1002885
198,56,7,4,2,57446,Life Expenses,1149760
199,36,4,4,1,43046,Other,861560

In [ ]:
import pandas as pd
import statsmodels.api as sm
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

# Number of rows
num_rows = 200

# Generate synthetic data
data = {
    'Age': np.random.randint(20, 65, num_rows),
    'No. of Family Members': np.random.randint(3, 8, num_rows),
    'Total Dependents': np.random.randint(1, 5, num_rows),
    'No. of Earners': np.random.randint(1, 4, num_rows),
    'Income': np.random.randint(30000, 80000, num_rows),
    'Reason for Loan': np.random.randint(1, 5, num_rows),
}

# Create DataFrame
df = pd.DataFrame(data)

# Map Reason for Loan to the specified categories
df['Reason for Loan'] = df['Reason for Loan'].map({
    1: 'Life Expenses',
    2: 'Education',
    3: 'Business',
    4: 'Other'
})

# Add Loan Amount based on a simple linear regression-like relationship
df['Loan Amount'] = 300 + 20 * df['Income'] + 10 * df['Age'] - 5 * df['Total Dependents']


# Define the independent variable (X) and dependent variable (y)
X = df[['Income', 'Age', 'Total Dependents', 'No. of Family Members']]
y = df['Loan Amount']

# Add a constant term to the independent variables
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Print the summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Loan Amount   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.843e+31
Date:                Mon, 26 Feb 2024   Prob (F-statistic):               0.00
Time:                        05:17:26   Log-Likelihood:                 4106.1
No. Observations:                 200   AIC:                            -8202.
Df Residuals:                     195   BIC:                            -8186.
Df Model:                           4
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                   300.0000   1.35e-10   2.22e+12      0.000     300.000     300.000
Income                   20.0000   1.45e-15   1.38e+16      0.000      20.000      20.000
Age                      10.0000   1.57e-12   6.38e+12      0.000      10.000      10.000
Total Dependents         -5.0000   1.78e-11   -2.8e+11      0.000      -5.000      -5.000
No. of Family Members  7.276e-12   1.53e-11      0.474      0.636    -2.3e-11    3.75e-11
==============================================================================
Omnibus:                        6.690   Durbin-Watson:                   1.462
Prob(Omnibus):                  0.035   Jarque-Bera (JB):                5.198
Skew:                          -0.286   Prob(JB):                       0.0743
Kurtosis:                       2.456   Cond. No.                     3.62e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.62e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Number of rows in the dataset
num_rows = 200

# Generate random data for the dataset
data = {
    'GND': np.random.choice([0, 1], size=num_rows),
    'GENDER': np.random.choice([0, 1], size=num_rows),
    'AGE': np.random.randint(18, 60, size=num_rows),
    'EDUCATION LEVEL' : np.random.randint(1, 5, size=num_rows),
    'NO OF FAMILY MEMBERS': np.random.randint(3, 7, size=num_rows),
    'TOTAL OF DEPENDENTS': np.random.randint(1, 5, size=num_rows),
    'NO OF EARNER': np.random.randint(1, 4, size=num_rows),
    'JOB': np.random.randint(1, 5, size=num_rows),
    'INCOME': np.random.randint(40000, 80000, size=num_rows),
    'REASON': np.random.randint(1, 5, size=num_rows),
    'LOAN AMOUNT': np.random.randint(5000, 30000, size=num_rows),
    'Loan Premium Value': np.random.randint(5000, 10000, size=num_rows),
    'Previous Loans': np.random.choice([0, 1], size=num_rows),
    'No of Previous Loans': np.random.randint(0, 5, size=num_rows),
    'Reasons for Previous Loan': np.random.randint(0, 5, size=num_rows),
    'Loan Policy Awarness': np.random.randint(0, 11, size=num_rows),
    'Effects of Loan': np.random.randint(0, 5, size=num_rows),
    'Loan impact on living': np.random.randint(0, 5, size=num_rows),
    'No of defaults in repayment of loan': np.random.choice([0, 1], size=num_rows),
    'Instant loan properly paid': np.random.choice([0, 1], size=num_rows),
    'Hoping to get loan future': np.random.choice([0, 1], size=num_rows),
    'Reasons for future loan': np.random.randint(0, 5, size=num_rows),
    'Your idea loans': np.random.randint(0, 5, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Map Reason for Loan to the specified categories
df['REASON'] = df['REASON'].map({
    1: 'Life Expenses',
    2: 'Education',
    3: 'Business',
    4: 'Other'
})

# Add Loan Amount based on a simple linear regression-like relationship
df['LOAN AMOUNT'] = 300 + 20 * df['INCOME'] + 10 * df['AGE'] - 5 * df['TOTAL OF DEPENDENTS']

# Display the entire DataFrame
df

,GND,GENDER,AGE,EDUCATION LEVEL,NO OF FAMILY MEMBERS,TOTAL OF DEPENDENTS,NO OF EARNER,JOB,INCOME,REASON,...,No of Previous Loans,Reasons for Previous Loan,Loan Policy Awarness,Effects of Loan,Loan impact on living,No of defaults in repayment of loan,Instant loan properly paid,Hoping to get loan future,Reasons for future loan,Your idea loans
0,0,0,41,1,5,4,1,2,52175,Education,...,4,3,4,3,1,0,1,1,2,1
1,1,1,28,3,3,4,1,1,61389,Other,...,0,0,4,1,1,0,1,1,4,4
2,0,0,25,3,6,2,1,1,40822,Life Expenses,...,1,3,7,1,2,1,0,1,2,2
3,0,0,53,1,4,2,2,3,57327,Education,...,4,4,7,0,0,0,0,0,0,4
4,0,1,55,4,3,2,1,4,46150,Life Expenses,...,1,3,6,4,0,1,0,1,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,41,1,4,4,2,2,69969,Life Expenses,...,4,1,9,2,0,0,1,1,4,4
196,1,1,29,3,5,3,3,4,53919,Life Expenses,...,4,0,5,3,3,1,0,1,1,4
197,1,1,52,1,5,1,2,4,43810,Education,...,1,3,6,1,2,0,0,1,4,1
198,0,1,50,3,5,2,1,2,70586,Other,...,4,0,2,0,3,1,1,1,4,1
199,0,0,50,1,4,1,2,3,79974,Business,...,1,1,6,2,4,0,1,1,1,4

In [ ]:
pip install pingouin

Requirement already satisfied: pingouin in /usr/local/lib/python3.10/dist-packages (0.5.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.11.4)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.5.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pingouin) (3.7.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.13.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.14.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.2.2)
Requirement already satisfied: pandas-flavor in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.6.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->pingouin) (2023.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pingouin) (3.1.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from pandas-flavor->pingouin) (2023.7.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (3.3.0)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels->pingouin) (0.5.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels->pingouin) (1.16.0)

In [ ]:
import pandas as pd
import numpy as np
import pingouin as pg

# Set a random seed for reproducibility
np.random.seed(42)

# Number of rows in the dataset
num_rows = 200

# Generate random data for the dataset
data = {
    'GND': np.random.choice([0, 1], size=num_rows),
    'GENDER': np.random.choice([0, 1], size=num_rows),
    'AGE': np.random.randint(18, 60, size=num_rows),
    'EDUCATION LEVEL': np.random.randint(1, 5, size=num_rows),
    'NO OF FAMILY MEMBERS': np.random.randint(3, 7, size=num_rows),
    'TOTAL OF DEPENDENTS': np.random.randint(1, 5, size=num_rows),
    'NO OF EARNER': np.random.randint(1, 4, size=num_rows),
    'JOB': np.random.randint(1, 5, size=num_rows),
    'INCOME': np.random.randint(40000, 80000, size=num_rows),
    'REASON': np.random.randint(1, 5, size=num_rows),
    'LOAN AMOUNT': np.random.randint(5000, 30000, size=num_rows),
    'Loan Premium Value': np.random.randint(5000, 10000, size=num_rows),
    'Previous Loans': np.random.choice([0, 1], size=num_rows),
    'No of Previous Loans': np.random.randint(0, 5, size=num_rows),
    'Reasons for Previous Loan': np.random.randint(0, 5, size=num_rows),
    'Loan Policy Awarness': np.random.randint(0, 11, size=num_rows),
    'Effects of Loan': np.random.randint(0, 5, size=num_rows),
    'Loan impact on living': np.random.randint(0, 5, size=num_rows),
    'No of defaults in repayment of loan': np.random.choice([0, 1], size=num_rows),
    'Instant loan properly paid': np.random.choice([0, 1], size=num_rows),
    'Hoping to get loan future': np.random.choice([0, 1], size=num_rows),
    'Reasons for future loan': np.random.randint(0, 5, size=num_rows),
    'Your idea loans': np.random.randint(0, 5, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Map Reason for Loan to the specified categories
df['REASON'] = df['REASON'].map({
    1: 'Life Expenses',
    2: 'Education',
    3: 'Business',
    4: 'Other'
})

# Add Loan Amount based on a simple linear regression-like relationship
df['LOAN AMOUNT'] = 300 + 20 * df['INCOME'] + 10 * df['AGE'] - 5 * df['TOTAL OF DEPENDENTS']

# Independent and dependent variables
independent_vars = ['AGE', 'JOB', 'GENDER', 'INCOME', 'EDUCATION LEVEL',
                    'REASON', 'No of Previous Loans', 'No of defaults in repayment of loan']
dependent_var = 'LOAN AMOUNT'

# Filter only numeric columns for Cronbach's alpha calculation
numeric_df = df[independent_vars].select_dtypes(include=np.number)

# Calculate Cronbach's alpha
alpha, items = pg.cronbach_alpha(numeric_df)

print(f"Cronbach's alpha value: {alpha:.3f}")
print("Individual items:", items)

Cronbach's alpha value: 0.000
Individual items: [-0.227  0.198]

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import pingouin as pg

# Set a random seed for reproducibility
np.random.seed(42)

# Number of rows in the dataset
num_rows = 150

# Generate random data for the dataset
data = {
    'GND': np.random.choice([0, 1], size=num_rows),
    'GENDER': np.random.choice([0, 1], size=num_rows),
    'AGE': np.random.randint(18, 60, size=num_rows),
    'EDUCATION LEVEL': np.random.randint(1, 5, size=num_rows),
    'NO OF FAMILY MEMBERS': np.random.randint(3, 7, size=num_rows),
    'TOTAL OF DEPENDENTS': np.random.randint(1, 5, size=num_rows),
    'NO OF EARNER': np.random.randint(1, 4, size=num_rows),
    'JOB': np.random.randint(1, 5, size=num_rows),
    'INCOME': np.random.randint(40000, 80000, size=num_rows),
    'REASON': np.random.randint(1, 5, size=num_rows),
    'LOAN AMOUNT': np.random.randint(5000, 30000, size=num_rows),
    'Loan Premium Value': np.random.randint(5000, 10000, size=num_rows),
    'Previous Loans': np.random.choice([0, 1], size=num_rows),
    'No of Previous Loans': np.random.randint(0, 5, size=num_rows),
    'Reasons for Previous Loan': np.random.randint(0, 5, size=num_rows),
    'Loan Policy Awareness': np.random.randint(0, 1, size=num_rows),
    'Effects of Loan': np.random.randint(0, 5, size=num_rows),
    'Loan impact on living': np.random.randint(0, 5, size=num_rows),
    'No of defaults in repayment of loan': np.random.choice([0, 1], size=num_rows),
    'Instant loan properly paid': np.random.choice([0, 1], size=num_rows),
    'Hoping to get loan future': np.random.choice([0, 1], size=num_rows),
    'Reasons for future loan': np.random.randint(0, 5, size=num_rows),
    'Your idea loans': np.random.randint(0, 5, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Adjust the multiplier randomly
multiplier = np.random.uniform(1, 10, size=num_rows)

# Ensure that Loan values are not larger than 500000
df['LOAN AMOUNT'] = np.where(df['LOAN AMOUNT'] > 500000, 500000, df['LOAN AMOUNT'])

# Ensure Loan Premium Value is at least 25% less than Income
df['Loan Premium Value'] = np.maximum(0.75 * df['INCOME'], df['Loan Premium Value'])

# Independent and dependent variables for regression
dependent_var = 'LOAN AMOUNT'
independent_vars = ['AGE', 'JOB', 'GENDER', 'INCOME', 'EDUCATION LEVEL', 'REASON',
                     'No of Previous Loans', 'No of defaults in repayment of loan']

# Convert to NumPy arrays
X = np.asarray(df[independent_vars])
y = np.asarray(df[dependent_var])

# Add constant to independent variables
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(y, X).fit()

# Print the summary statistics
print(model.summary())

# Calculate Cronbach's alpha
alpha, items = pg.cronbach_alpha(df[independent_vars])
print(f"Cronbach's alpha value: {alpha:.3f}")

# Perform skewness test
from scipy.stats import skew

skewness = skew(df[dependent_var])
print(f"Skewness: {skewness:.3f}")

# Perform significance test
# anova = pg.anova(dv=dependent_var, between=independent_vars, data=df)
# print(anova)

# Add Loan Amount based on a simple linear regression-like relationship
df['LOAN AMOUNT'] = 300 + 20 * df['INCOME'] + 10 * df['AGE'] - 5 * df['TOTAL OF DEPENDENTS']

# Display the entire DataFrame
df

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.052
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.9643
Date:                Mon, 26 Feb 2024   Prob (F-statistic):              0.466
Time:                        08:00:32   Log-Likelihood:                -1540.4
No. Observations:                 150   AIC:                             3099.
Df Residuals:                     141   BIC:                             3126.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.042e+04   4569.836      2.280      0.024    1385.311    1.95e+04
x1           121.1211     50.440      2.401      0.018      21.404     220.838
x2           126.8091    551.238      0.230      0.818    -962.950    1216.568
x3          -358.6153   1242.803     -0.289      0.773   -2815.551    2098.320
x4             0.0521      0.050      1.037      0.301      -0.047       0.151
x5            59.9618    527.995      0.114      0.910    -983.847    1103.771
x6          -146.4493    541.244     -0.271      0.787   -1216.451     923.553
x7          -256.0687    434.642     -0.589      0.557   -1115.325     603.188
x8          1014.1588   1212.619      0.836      0.404   -1383.106    3411.423
==============================================================================
Omnibus:                       48.188   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                8.533
Skew:                          -0.098   Prob(JB):                       0.0140
Kurtosis:                       1.848   Cond. No.                     4.64e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.64e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
Cronbach's alpha value: -0.000
Skewness: -0.143

,GND,GENDER,AGE,EDUCATION LEVEL,NO OF FAMILY MEMBERS,TOTAL OF DEPENDENTS,NO OF EARNER,JOB,INCOME,REASON,...,No of Previous Loans,Reasons for Previous Loan,Loan Policy Awareness,Effects of Loan,Loan impact on living,No of defaults in repayment of loan,Instant loan properly paid,Hoping to get loan future,Reasons for future loan,Your idea loans
0,0,0,50,4,3,1,1,3,50167,2,...,3,4,0,0,4,0,0,1,2,4
1,1,0,18,1,5,3,2,4,50554,3,...,0,1,0,3,4,1,0,1,3,1
2,0,0,36,1,6,4,2,3,57260,3,...,2,1,0,3,1,1,0,1,1,1
3,0,0,19,3,3,1,2,3,43812,3,...,2,2,0,4,0,1,1,0,0,2
4,0,0,43,2,4,4,2,3,68024,3,...,0,4,0,2,3,0,0,0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0,1,44,4,5,4,1,2,60103,2,...,4,3,0,2,3,1,1,1,0,0
146,0,1,59,4,4,4,2,4,54382,3,...,1,1,0,4,4,1,1,0,1,2
147,0,0,19,2,5,4,1,2,58755,3,...,2,2,0,1,1,1,1,0,4,3
148,0,0,43,2,6,2,2,4,75659,3,...,4,4,0,1,2,0,1,0,0,0
149,1,1,34,4,3,4,3,2,43756,4,...,0,4,0,3,1,1,1,1,3,1

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import pingouin as pg

# Set a random seed for reproducibility
np.random.seed(42)

# Number of rows in the dataset
num_rows = 150

# Generate random data for the dataset
data = {
    'GND': np.random.choice([0, 1], size=num_rows),
    'GENDER': np.random.choice([0, 1], size=num_rows),
    'AGE': np.random.randint(18, 60, size=num_rows),
    'EDUCATION LEVEL': np.random.choice([1, 2, 3, 4], size=num_rows),  # Include all education levels
    'NO OF FAMILY MEMBERS': np.random.randint(3, 7, size=num_rows),
    'TOTAL OF DEPENDENTS': np.random.randint(1, 5, size=num_rows),
    'NO OF EARNER': np.random.randint(1, 4, size=num_rows),
    'JOB': np.random.randint(1, 5, size=num_rows),
    'INCOME': np.round(np.random.uniform(40000, 80000, size=num_rows), -3),  # Round to the nearest thousand
    'REASON': np.random.choice([1, 2, 3, 4], size=num_rows),  # Include all reasons
    'LOAN AMOUNT': np.round(np.random.uniform(5000, 30000, size=num_rows), -3),  # Round to the nearest thousand
    'Loan Premium Value': np.round(np.random.uniform(5000, 10000, size=num_rows), -3),  # Round to the nearest thousand
    'Previous Loans': np.random.choice([0, 1], size=num_rows),
    'No of Previous Loans': np.random.randint(0, 5, size=num_rows),
    'Reasons for Previous Loan': np.random.randint(0, 5, size=num_rows),
    'Loan Policy Awareness': np.random.randint(0, 1, size=num_rows),
    'Effects of Loan': np.random.randint(0, 5, size=num_rows),
    'Loan impact on living': np.random.randint(0, 5, size=num_rows),
    'No of defaults in repayment of loan': np.random.choice([0, 1], size=num_rows),
    'Instant loan properly paid': np.random.choice([0, 1], size=num_rows),
    'Hoping to get loan future': np.random.choice([0, 1], size=num_rows),
    'Reasons for future loan': np.random.randint(0, 5, size=num_rows),
    'Your idea loans': np.random.randint(0, 5, size=num_rows)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Adjust the multiplier randomly
multiplier = np.random.uniform(1, 10, size=num_rows)

# Ensure that Loan values are not larger than 500000
df['LOAN AMOUNT'] = np.where(df['LOAN AMOUNT'] > 500000, 500000, df['LOAN AMOUNT'])

# Ensure Loan Premium Value is at least 25% less than Income
df['Loan Premium Value'] = np.maximum(0.75 * df['INCOME'], df['Loan Premium Value'])

# Round values to the nearest thousand
df[['INCOME', 'LOAN AMOUNT', 'Loan Premium Value']] = df[['INCOME', 'LOAN AMOUNT', 'Loan Premium Value']].round(-3)

# Independent and dependent variables for regression
dependent_var = 'LOAN AMOUNT'
independent_vars = ['AGE', 'JOB', 'GENDER', 'INCOME', 'EDUCATION LEVEL', 'REASON',
                     'No of Previous Loans', 'No of defaults in repayment of loan']

# Convert to NumPy arrays
X = np.asarray(df[independent_vars])
y = np.asarray(df[dependent_var])

# Add constant to independent variables
X = sm.add_constant(X)

# Calculate Cronbach's alpha
alpha, items = pg.cronbach_alpha(df[independent_vars])
print(f"Cronbach's alpha value: {alpha:.3f}")

# Display the entire DataFrame
df

Cronbach's alpha value: -0.000

,GND,GENDER,AGE,EDUCATION LEVEL,NO OF FAMILY MEMBERS,TOTAL OF DEPENDENTS,NO OF EARNER,JOB,INCOME,REASON,...,No of Previous Loans,Reasons for Previous Loan,Loan Policy Awareness,Effects of Loan,Loan impact on living,No of defaults in repayment of loan,Instant loan properly paid,Hoping to get loan future,Reasons for future loan,Your idea loans
0,0,0,50,4,3,1,1,3,50000.0,1,...,4,0,0,0,2,1,0,1,0,4
1,1,0,18,1,5,3,2,4,60000.0,1,...,4,3,0,2,3,1,1,0,0,0
2,0,0,36,1,6,4,2,3,53000.0,2,...,1,1,0,4,4,1,0,0,3,1
3,0,0,19,3,3,1,2,3,77000.0,2,...,2,2,0,1,1,0,0,1,3,3
4,0,0,43,2,4,4,2,3,40000.0,4,...,4,4,0,1,2,1,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0,1,44,4,5,4,1,2,43000.0,1,...,3,1,0,4,4,0,0,0,3,3
146,0,1,59,4,4,4,2,4,44000.0,4,...,1,2,0,3,3,1,0,0,4,4
147,0,0,19,2,5,4,1,2,74000.0,2,...,0,2,0,2,3,0,0,1,3,1
148,0,0,43,2,6,2,2,4,76000.0,1,...,2,1,0,4,4,0,1,1,3,2
149,1,1,34,4,3,4,3,2,45000.0,3,...,0,1,0,1,3,0,0,0,2,0

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.